In [1]:
import numpy as np

In [2]:
x=np.zeros(10)

In [3]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
x=np.arange(10,49)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [7]:
x.shape

(39,)

In [9]:
x.dtype

dtype('int32')

In [11]:
print(np.__version__)
print(np.show_config())

1.15.1
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sheraz Manzoor/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/Sheraz Manzoor/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Sheraz Manzoor/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_201

In [12]:
x.ndim

1

In [15]:
y=np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [17]:
z=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(z)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [19]:
x1=np.array([2,4,5])
x2=x1[::-1]
print(x1)
print(x2)

[2 4 5]
[5 4 2]


In [29]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [31]:
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
x = np.array([1, 2, 3, 4, 5])
print(x.astype(float))
x.dtype

[1. 2. 3. 4. 5.]


dtype('int32')

In [51]:
x= np.array([[12.0, 12.51], [2.34, 7.98], [25.23, 36.50]])
print(x)
print(x.astype(int))

[[12.   12.51]
 [ 2.34  7.98]
 [25.23 36.5 ]]
[[12 12]
 [ 2  7]
 [25 36]]


In [ ]:
Convert the data type of the given array from int to float

In [61]:
y1 = np.array([[1., 2., 3.],[4., 5., 6.]])  

y2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print(y1)
print(y2)
y = y1*y2
print(y)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[ 0.  8.  3.]
 [28. 10. 72.]]


In [66]:
comparison=y1==y2
print(comparison)

[[False False False]
 [False False False]]


In [ ]:
Extract all odd numbers from arr with values(0-9)
Extract all odd numbers from arr with values(0-9)lo

In [9]:
import numpy as np

In [17]:
arr=np.arange(10)
arr[4:8]=12
print(arr)

[ 0  1  2  3 12 12 12 12  8  9]


In [76]:
import numpy as np
x=np.ones((4,4))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [19]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]=12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


In [21]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
print(arr3d)

[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


In [47]:
arr4 = np.arange(10).reshape(2,5)
print(arr4)
y=arr4[0]
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]


In [43]:
arr4 = np.arange(10).reshape(2,5)
print(arr4)
y=arr4[1,1]
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
6


In [51]:
arr4 = np.arange(10).reshape(2,5)
print(arr4)
y=arr4[:,2]
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[2 7]


In [61]:
arr5=np.random.randn(10,10)
print(arr5)

[[-1.15662404  0.70121784 -0.86069936 -1.56994299 -3.63743357 -1.20728233
   0.72314644 -0.72684634  0.3336113  -1.30799165]
 [ 0.26906247  2.17624204 -0.43455212 -0.87353597 -0.24345568 -0.57064247
   0.35187069 -1.16719555  0.29370739  0.21447991]
 [-0.39339679  1.64281854 -0.22977385  0.54751379  1.93434412  0.83322113
   1.13313439 -0.46151904  0.29690527  0.12985362]
 [ 0.06432273 -0.29656694 -0.75085681  0.46169683 -0.62372838  0.67768275
   0.64875524  0.59631192  1.00572746 -0.51662511]
 [-1.01357938  2.81647862 -0.80502729  0.2722039   2.43883482  1.6374389
  -0.19448858  1.37793442  0.97891792  0.12473289]
 [ 0.59442063  0.76152226  0.4245893   0.40205111  1.29206749 -0.551391
  -0.13855074  0.18204591  1.17706302 -0.10754935]
 [ 0.40466577  1.26260698  1.85927159 -1.07197094 -1.15117807 -0.6191822
  -0.4605051   0.10399458  0.54905162  0.25996048]
 [-0.36476532 -1.39822654  0.81783696 -0.29181105 -0.48935795  1.7592532
  -0.63169926 -0.00890471  0.16688646 -0.13720361]
 [-0.

In [66]:
arr5.min()

-3.637433573647877

In [67]:
arr5.max()

2.8164786151776293

In [ ]:

Find all the values from array data where the values from array names are not equal to Will

In [69]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.intersect1d(a,b)
print(common)


[2 4]


In [79]:
A = np.array([1,2,3,2,3,4,3,4,5,6]) 
B = np.array([7,2,10,2,7,4,9,4,9,8])
commonposition = np.searchsorted(A,B)
print(commonposition)

[10  1 10  1 10  5 10  5 10 10]


In [80]:
np.searchsorted(A, np.intersect1d(A, B))

array([1, 5], dtype=int64)

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

In [87]:
import numpy as np
x=np.arange(1,16).reshape(3,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [90]:
x1=np.arange(1,17).reshape(2,2,4)
print(x1)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [91]:
x2=np.arange(1,17).reshape(4,2,2)
print(x2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [97]:
x3=np.array([0,1,2,3,4,5,6,7,8,9])
x4=np.sqrt(x3)
print(x4)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [116]:
x5=np.random.randn(12)
X5=np.random.randn(12)
print(X5)
print(x5)

[ 2.69904421  0.71977589 -1.00705486  1.37150088  0.52955045  0.39804088
  1.21692217 -1.3675885   0.87517671  0.32811314  0.64920107  0.08759422]
[-0.30023596 -0.2083361  -0.76666613 -0.01930868 -0.68833656 -1.16816067
 -0.22428348 -0.18041858  0.24339362  0.10971843  0.07225397  0.74973049]


In [117]:
x7=np.array([x5.max(),X5.max()])
print(x7)

[0.74973049 2.69904421]


In [103]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z=np.dot(x,y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


In [108]:
x6=np.random.randn(20,20)
x6.cumsum()

array([-1.04445980e+00,  3.01174189e-02,  1.36876830e-02, -1.00181439e-01,
       -1.24957677e+00, -4.27067986e-02, -1.97134941e-01,  1.97049863e-01,
        1.97905982e-01,  9.18093604e-01,  1.21390219e+00,  9.98176590e-01,
        1.59923518e+00,  5.32671266e-01, -1.18324976e+00, -3.20597033e+00,
       -2.85650049e+00, -2.76779266e+00, -3.36482404e+00, -4.38258480e+00,
       -4.24732988e+00, -4.95113599e+00, -4.30292521e+00, -3.69578437e+00,
       -4.02386626e+00, -5.98359219e+00, -6.21497364e+00, -5.13826009e+00,
       -4.89003081e+00, -6.05269178e+00, -7.55334721e+00, -6.37001745e+00,
       -6.63511311e+00, -7.84105369e+00, -7.54224029e+00, -6.24378679e+00,
       -7.64122280e+00, -7.43415662e+00, -7.12067991e+00, -7.74705226e+00,
       -8.13526995e+00, -8.34725403e+00, -9.12516727e+00, -8.82646488e+00,
       -7.20486544e+00, -6.95504392e+00, -7.91060361e+00, -7.96460798e+00,
       -9.61859781e+00, -9.15225288e+00, -1.07329899e+01, -1.13088742e+01,
       -1.06101668e+01, -